# Support Vector Regression (SVR)

## Importing the libraries

In [173]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [174]:
dataset = pd.read_csv('df_patients_v20220321 - df_patients_v20220321.csv')
X = dataset.drop(columns=['DocID','PtID','P8','P9'])
X = X.iloc[:,:].values
y = dataset.iloc[:, 10].values

## Encoding categorical data

### Encoding the Independent Variable

In [175]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [176]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [177]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [178]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [11])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [179]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [-1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

## Splitting the dataset into the Training set and Test set

In [180]:
print(X)

[[1.0 0.0 0.0 ... 1 27 11]
 [1.0 0.0 0.0 ... 3 22 5]
 [1.0 0.0 0.0 ... 3 22 5]
 ...
 [0.0 1.0 0.0 ... 2 23 9]
 [0.0 1.0 0.0 ... 3 25 12]
 [0.0 1.0 0.0 ... 2 29 13]]


In [181]:
print(y)

[10  6 10 ...  2  1  7]


In [182]:
y = y.reshape(len(y),1)

In [183]:
print(y)

[[10]
 [ 6]
 [10]
 ...
 [ 2]
 [ 1]
 [ 7]]


In [184]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [185]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
X_trainTransformed = sc_x.fit_transform(X_train[:, -3:])
X_train = np.concatenate([X_train[:,:-3], X_trainTransformed], axis=1)
X_testTransformed = sc_x.transform(X_test[:, -3:])
X_test = np.concatenate([X_test[:,:-3], X_testTransformed], axis=1)
y_train = sc_y.fit_transform(y_train)
y_test = sc_y.transform(y_test)

## Training the SVR model on the training set

In [186]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf', degree = 4, )
regressor.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(degree=4, gamma='auto')

## Predicting the Test set results

In [187]:
y_pred = regressor.predict(X_test)
y_pred = np.reshape(y_pred, (len(y_pred),1))

In [188]:
y_pred = sc_y.inverse_transform(y_pred)
y_test = sc_y.inverse_transform(y_test)
from sklearn.metrics import mean_squared_error
errors = mean_squared_error(y_test, y_pred)
print(errors)

42.91990029430404
